name: Conventional commit

on:
    pull_request:
        types: [opened, edited]

jobs:
    main:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              id: check_pr_rule
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  types: |
                      build
                      chore
                      ci
                      docs
                      feat
                      fix
                      perf
                      refactor
                      revert
                      style
                      test
                  requireScope: false
                  subjectPattern: ^(?![A-Z]).+$
                  subjectPatternError: The subject must start with a lowercase character
            # Create a sticky comment to display the detailed error
            - uses: marocchino/sticky-pull-request-comment@v2
              if: always() && (steps.check_pr_rule.outputs.error_message != null)
              with:
                  header: check_pr_comment
                  message: |
                      Pull request titles must follow the [Conventional Commits specification](https://www.conventionalcommits.org/).
                      Please adjust your title following:
                      ```
                      ${{ steps.check_pr_rule.outputs.error_message }}
                      ```
            # Delete a previous comment when the issue has been resolved
            - if: ${{ steps.check_pr_rule.outputs.error_message == null }}
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: check_pr_comment
                  delete: true
